# Generated by Django 2.2 on 2019-04-22 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='note',
            name='body',
            field=models.TextField(verbose_name='Текст заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Заголовок заметки'),
        ),
        migrations.AlterField(
            model_name='note',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='notes', to='notes.Tag', verbose_name='Теги'),
        ),
        migrations.AlterField(
            model_name='tag',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Тег'),
        ),
    ]
