# Generated by Django 2.2 on 2019-05-01 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0006_auto_20190501_1824'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tag',
            order_with_respect_to='label',
        ),
    ]
