# Generated by Django 2.2 on 2019-05-01 15:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0007_auto_20190501_1845'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='tag',
            order_with_respect_to=None,
        ),
    ]
